# Generated by Django 6.0.5 on 2026-05-30 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("music_queue", "0001_initial"),
        ("tenants", "0001_initial"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pincode",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pin_codes",
                to="venues.table",
            ),
        ),
        migrations.AddField(
            model_name="pincode",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pin_codes",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="playbackqueue",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playback_queue",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="playbackqueue",
            name="current_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="music_queue.request",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="table",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="venues.table",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="music_queue.session",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="music_queue.track",
            ),
        ),
    ]
