# Generated by Django 6.0.5 on 2026-05-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "tenant_type",
                    models.CharField(
                        choices=[
                            ("BAR", "Bar"),
                            ("NIGHTCLUB", "Nightclub"),
                            ("RESTAURANT", "Restaurant"),
                        ],
                        default="BAR",
                        max_length=50,
                    ),
                ),
                (
                    "spotify_client_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "spotify_client_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
